
import { Subject, Exam } from './types';

export const SUBJECTS: Subject[] = [
  { id: 'math', name: { ar: 'الرياضيات', en: 'Mathematics' }, icon: '📐', color: 'bg-blue-500' },
  { id: 'science', name: { ar: 'العلوم', en: 'Science' }, icon: '🧪', color: 'bg-green-500' },
  { id: 'history', name: { ar: 'التاريخ', en: 'History' }, icon: '📜', color: 'bg-amber-500' },
  { id: 'english', name: { ar: 'اللغة الإنجليزية', en: 'English Language' }, icon: '✍️', color: 'bg-emerald-500' },
];

export const TRANSLATIONS = {
  ar: {
    dashboard: 'لوحة التحكم',
    startExam: 'ابدأ الاختبار',
    totalExams: 'إجمالي الاختبارات',
    accuracy: 'معدل الدقة',
    progress: 'التقدم',
    lastScore: 'آخر درجة',
    noExams: 'لم يتم إجراء اختبارات بعد',
    next: 'التالي',
    previous: 'السابق',
    submit: 'إنهاء الاختبار',
    backToHome: 'العودة للرئيسية',
    score: 'النتيجة النهائية',
    timeSpent: 'الوقت المستغرق',
    correctAnswers: 'الإجابات الصحيحة',
    wrongAnswers: 'الإجابات الخاطئة',
    review: 'مراجعة الإجابات',
    checking: 'جاري التحقق...',
    check: 'تحقق من الإجابة',
    yourAnswer: 'إجابتك',
    correctAnswer: 'الإجابة الصحيحة',
    langToggle: 'English',
    themeToggle: 'تغيير الوضع',
    examHistory: 'سجل الاختبارات',
    date: 'التاريخ',
    subject: 'المادة',
    stats: 'الإحصائيات الشاملة',
    correct: 'صحيح',
    wrong: 'خطأ',
    placement_title: 'امتحان تحديد المستوى',
    placement_desc: 'ابدأ بتقييم مستواك العام للحصول على خطة دراسية مخصصة.',
    placement_btn: 'ابدأ التقييم الآن',
    delete: 'حذف',
    open: 'فتح المراجعة',
    wrongOften: 'أسئلة تخطئ فيها غالباً',
    subjectStats: 'إحصائيات المادة',
    starred_exam: 'اختبار المفضلة',
    starred_desc: 'امتحن نفسك في الأسئلة التي قمت بتمييزها بنجمة من قبل.',
    show_all: 'عرض الكل',
    show_wrong: 'الأخطاء فقط',
    no_starred: 'لا توجد أسئلة في المفضلة بعد. اضغط على النجمة أثناء الحل لإضافتها!',
    my_favorites: 'قائمة المفضلة',
    fav_questions: 'الأسئلة المحفوظة',
    start_fav_test: 'بدء اختبار المفضلة',
    add_to_fav: 'إضافة للمفضلة',
    remove_from_fav: 'إزالة من المفضلة'
  },
  en: {
    dashboard: 'Dashboard',
    startExam: 'Start Exam',
    totalExams: 'Total Exams',
    accuracy: 'Accuracy Rate',
    progress: 'Progress',
    lastScore: 'Last Score',
    noExams: 'No exams taken yet',
    next: 'Next',
    previous: 'Previous',
    submit: 'Finish Exam',
    backToHome: 'Back to Home',
    score: 'Final Score',
    timeSpent: 'Time Spent',
    correctAnswers: 'Correct Answers',
    wrongAnswers: 'Wrong Answers',
    review: 'Review Answers',
    checking: 'Checking...',
    check: 'Check Answer',
    yourAnswer: 'Your Answer',
    correctAnswer: 'Correct Answer',
    langToggle: 'العربية',
    themeToggle: 'Toggle Theme',
    examHistory: 'Exam History',
    date: 'Date',
    subject: 'Subject',
    stats: 'Overall Statistics',
    correct: 'Correct',
    wrong: 'Wrong',
    placement_title: 'Placement Exam',
    placement_desc: 'Start by assessing your overall level to get a personalized study plan.',
    placement_btn: 'Start Assessment Now',
    delete: 'Delete',
    open: 'Open Review',
    wrongOften: 'Frequently Wrong Questions',
    subjectStats: 'Subject Stats',
    starred_exam: 'Starred Challenge',
    starred_desc: 'Test yourself only on the questions you previously starred.',
    show_all: 'Show All',
    show_wrong: 'Wrong Only',
    no_starred: 'No starred questions yet. Click the star during exams to add some!',
    my_favorites: 'My Favorites',
    fav_questions: 'Saved Questions',
    start_fav_test: 'Start Favorites Test',
    add_to_fav: 'Add to Favorites',
    remove_from_fav: 'Remove from Favorites'
  }
};
