
import { Subject, Exam } from './types';

export const SUBJECTS: Subject[] = [];

export const ETHICS_EXAM: Exam = {
  id: 'ethics_101',
  subjectId: 'ethics',
  title: { ar: 'امتحان أخلاقيات المهنة الشامل', en: 'Professional Ethics Exam' },
  active: true,
  thumbnail: '⚖️',
  questions: [
    // --- (1) 36 Multiple Choice Questions ---
    { id: 'q1', type: 'multiple-choice', questionText: { ar: 'مفهوم الأخلاق هو:', en: 'Ethics concept is:' }, options: [{ ar: 'أ) مجموعة من القيم والمبادئ التي تحدد سلوك الفرد وتوجهه', en: 'A' }, { ar: 'ب) قواعد سياسية لضبط سلوك الدولة', en: 'B' }, { ar: 'ج) قوانين مهنية تنظم العلاقة بين أصحاب المهن', en: 'C' }], correctAnswer: '0' },
    { id: 'q2', type: 'multiple-choice', questionText: { ar: 'النظرية الفطرية الطبيعية ترى أن:', en: 'Innate theory sees:' }, options: [{ ar: 'أ) الأخلاق مكتسبة بالتجربة', en: 'A' }, { ar: 'ب) الأخلاق ثابتة نابعة من ذات الإنسان وفطرته', en: 'B' }, { ar: 'ج) الأخلاق لا علاقة لها بالتربية', en: 'C' }], correctAnswer: '1' },
    { id: 'q3', type: 'multiple-choice', questionText: { ar: 'يشترط بالفعل الخلقي حتى يكون دليلاً على الأخلاق أن:', en: 'Moral act requirement:' }, options: [{ ar: 'أ) يصدر بتكرار وبإرادة حرة', en: 'A' }, { ar: 'ب) يكون مرة واحدة فقط', en: 'B' }, { ar: 'ج) يصدر بالإكراه', en: 'C' }], correctAnswer: '0' },
    { id: 'q4', type: 'multiple-choice', questionText: { ar: 'من وسائل اكتساب الأخلاق:', en: 'Means of acquiring ethics:' }, options: [{ ar: 'أ) التعليم والخبرة الشخصية', en: 'A' }, { ar: 'ب) الاستسلام للوراثة فقط', en: 'B' }, { ar: 'ج) تجاهل القيم المجتمعية', en: 'C' }], correctAnswer: '0' },
    { id: 'q5', type: 'multiple-choice', questionText: { ar: 'العلاقة بين الأخلاق العامة وأخلاقيات المهنة هي:', en: 'Relation between ethics types:' }, options: [{ ar: 'أ) الأخلاق العامة جزء من أخلاقيات المهنة', en: 'A' }, { ar: 'ب) أخلاقيات المهنة جزء من الأخلاق العامة', en: 'B' }, { ar: 'ج) لا توجد علاقة بينهما', en: 'C' }], correctAnswer: '1' },
    { id: 'q6', type: 'multiple-choice', questionText: { ar: 'النظرية الاكتسابية تعتبر أن الإنسان يولد:', en: 'Acquisition theory says:' }, options: [{ ar: 'أ) ممتلئا بالأخلاق الفاضلة', en: 'A' }, { ar: 'ب) ممتلئا بالأخلاق السيئة', en: 'B' }, { ar: 'ج) صفحة بيضاء يكتسب منها الأخلاق بالتربية والتجارب', en: 'C' }], correctAnswer: '2' },
    { id: 'q7', type: 'multiple-choice', questionText: { ar: 'مجموعة من السمات الأساسية التي تتطلب مهارة عالية ومعرفة متخصصة:', en: 'Traits requiring skill:' }, options: [{ ar: 'أ) المهنة', en: 'A' }, { ar: 'ب) الوظيفة', en: 'B' }, { ar: 'ج) العمل', en: 'C' }], correctAnswer: '0' },
    { id: 'q8', type: 'multiple-choice', questionText: { ar: 'أن يستحضر الشخص النية الصالحة في العمل:', en: 'Good intention at work:' }, options: [{ ar: 'أ) التواضع', en: 'A' }, { ar: 'ب) الصدق', en: 'B' }, { ar: 'ج) الاخلاص', en: 'C' }], correctAnswer: '2' },
    { id: 'q9', type: 'multiple-choice', questionText: { ar: 'خلق يعف الإنسان عما ليس له به حق:', en: 'Refraining from non-rights:' }, options: [{ ar: 'أ) الصدق', en: 'A' }, { ar: 'ب) الأمانة', en: 'B' }, { ar: 'ج) الاخلاص', en: 'C' }], correctAnswer: '1' },
    { id: 'q10', type: 'multiple-choice', questionText: { ar: 'من مصادر أخلاقيات المهنة:', en: 'Sources of ethics:' }, options: [{ ar: 'أ) المصدر الاقتصادي', en: 'A' }, { ar: 'ب) المصدر الديني', en: 'B' }, { ar: 'ج) جميع ما سبق', en: 'C' }], correctAnswer: '2' },
    { id: 'q11', type: 'multiple-choice', questionText: { ar: 'تعمل على وقاية الفرد من الإنحراف وتدعم الثقة في النفس وثقته بالمنظمة والمجتمع:', en: 'Prevents deviation:' }, options: [{ ar: 'أ) أهمية أخلاقيات المهنة على مستوى الفرد', en: 'A' }, { ar: 'ب) أهمية أخلاقيات المهنة على مستوي المجتمع', en: 'B' }, { ar: 'ج) أهمية أخلاقيات المهنة على مستوي العمل', en: 'C' }], correctAnswer: '0' },
    { id: 'q12', type: 'multiple-choice', questionText: { ar: 'يدعم الرضا والاستقرار الاجتماعي بين غالبية الناس حيث يحصل كل ذي حق علي حقة ويسود العدل:', en: 'Supports social stability:' }, options: [{ ar: 'أ) أهمية أخلاقيات المهنة علي مستوي الفرد', en: 'A' }, { ar: 'ب) أهمية أخلاقيات المهنة على مستوى المجتمع', en: 'B' }, { ar: 'ج) أهمية أخلاقيات المهنة على مستوي العمل', en: 'C' }], correctAnswer: '1' },
    { id: 'q13', type: 'multiple-choice', questionText: { ar: 'تساعد في فهم الواجبات المهنية والتذكير بنظام الثواب والعقاب كإحدي الوسائل الناجحة:', en: 'Helps understanding duties:' }, options: [{ ar: 'أ) أهمية أخلاقيات المهنة علي مستوي الفرد', en: 'A' }, { ar: 'ب) أهمية أخلاقيات المهنة علي مستوي المجتمع', en: 'B' }, { ar: 'ج) أهمية أخلاقيات المهنة على مستوى العمل', en: 'C' }], correctAnswer: '2' },
    { id: 'q14', type: 'multiple-choice', questionText: { ar: 'من وسائل ترسيخ أخلاقيات المهنة:', en: 'Consolidating ethics:' }, options: [{ ar: 'أ) القدوة الحسنة', en: 'A' }, { ar: 'ب) استغلال المنصب', en: 'B' }, { ar: 'ج) الهدايا والضيافة', en: 'C' }], correctAnswer: '0' },
    { id: 'q15', type: 'multiple-choice', questionText: { ar: 'الانفراد بالرأي أو التسلط من تحديات أخلاقيات المهنة:', en: 'Challenges:' }, options: [{ ar: 'أ) التحديات الداخلية', en: 'A' }, { ar: 'ب) التحديات الخارجية', en: 'B' }, { ar: 'ج) التحديات العامة', en: 'C' }], correctAnswer: '0' },
    { id: 'q16', type: 'multiple-choice', questionText: { ar: 'تعد مهنة التعليم مهنة سامية لأنها تقوم على:', en: 'Teaching is noble:' }, options: [{ ar: 'أ) نقل المعلومات فقط', en: 'A' }, { ar: 'ب) تحقيق الأرباح', en: 'B' }, { ar: 'ج) بناء الإنسان وتنمية القيم', en: 'C' }], correctAnswer: '2' },
    { id: 'q17', type: 'multiple-choice', questionText: { ar: 'من أهم أخلاقيات مهنة التعليم:', en: 'Teaching ethics:' }, options: [{ ar: 'أ) التحيز لبعض الطلاب', en: 'A' }, { ar: 'ب) العدالة والإنصاف', en: 'B' }, { ar: 'ج) الغش', en: 'C' }], correctAnswer: '1' },
    { id: 'q18', type: 'multiple-choice', questionText: { ar: 'احترام التنوع بين الطلاب يعني أن المعلم:', en: 'Respecting diversity:' }, options: [{ ar: 'أ) يفرق في المعاملة', en: 'A' }, { ar: 'ب) يتجاهل الفروق الفردية', en: 'B' }, { ar: 'ج) يعامل الطلاب بعدالة واحترام', en: 'C' }], correctAnswer: '2' },
    { id: 'q19', type: 'multiple-choice', questionText: { ar: 'من صفات المعلم القدوة الأخلاقية:', en: 'Role model teacher traits:' }, options: [{ ar: 'أ) العصبية الدائمة', en: 'A' }, { ar: 'ب) الصبر والعدل', en: 'B' }, { ar: 'ج) التهاون', en: 'C' }], correctAnswer: '1' },
    { id: 'q20', type: 'multiple-choice', questionText: { ar: 'من واجبات المعلم تجاه طلابه:', en: 'Teacher duties:' }, options: [{ ar: 'أ) كشف أسرارهم', en: 'A' }, { ar: 'ب) الاستهزاء بهم', en: 'B' }, { ar: 'ج) احترام خصوصيتهم', en: 'C' }], correctAnswer: '2' },
    { id: 'q21', type: 'multiple-choice', questionText: { ar: 'الصدق في تقييم الطلاب يعني أن المعلم:', en: 'Honesty in evaluation:' }, options: [{ ar: 'أ) يجامل الطلاب', en: 'A' }, { ar: 'ب) يقيمهم وفق معايير عادلة', en: 'B' }, { ar: 'ج) يعتمد على الحظ', en: 'C' }], correctAnswer: '1' },
    { id: 'q22', type: 'multiple-choice', questionText: { ar: 'العدالة في التعليم تظهر عندما:', en: 'Justice in education:' }, options: [{ ar: 'أ) يفضل المعلم المتفوقين فقط', en: 'A' }, { ar: 'ب) يساوي بين جميع الطلاب', en: 'B' }, { ar: 'ج) يتعامل بحدة مع الجميع', en: 'C' }], correctAnswer: '1' },
    { id: 'q23', type: 'multiple-choice', questionText: { ar: 'من الأخلاقيات الواجب تجنبها في مهنة التعليم:', en: 'Avoid in teaching:' }, options: [{ ar: 'أ) الأمانة', en: 'A' }, { ar: 'ب) التحيز', en: 'B' }, { ar: 'ج) الصبر', en: 'C' }], correctAnswer: '1' },
    { id: 'q24', type: 'multiple-choice', questionText: { ar: 'يجب على المعلم أن يكون نموذجا:', en: 'Teacher as a model:' }, options: [{ ar: 'أ) في السلوك المهني والأخلاقي', en: 'A' }, { ar: 'ب) في التفوق الدراسي فقط', en: 'B' }, { ar: 'ج) في الحزم الشديد فقط', en: 'C' }], correctAnswer: '0' },
    { id: 'q25', type: 'multiple-choice', questionText: { ar: 'من مهام المعلم الأخلاقية داخل الصف:', en: 'Moral tasks in class:' }, options: [{ ar: 'أ) فرض رأيه فقط', en: 'A' }, { ar: 'ب) تشجيع الحوار والنقاش', en: 'B' }, { ar: 'ج) تجاهل آراء الطلاب', en: 'C' }], correctAnswer: '1' },
    { id: 'q26', type: 'multiple-choice', questionText: { ar: 'ما المقصود بأخلاقيات الإدارة التعليمية:', en: 'Admin ethics definition:' }, options: [{ ar: 'أ) القوانين المنظمة للعمل فقط', en: 'A' }, { ar: 'ب) القيم والمبادئ التي تحكم السلوك الإداري', en: 'B' }, { ar: 'ج) التعليمات الوزارية', en: 'C' }], correctAnswer: '1' },
    { id: 'q27', type: 'multiple-choice', questionText: { ar: 'التعاون مع أولياء الأمور والمجتمع المحلي يهدف إلى:', en: 'Cooperation goal:' }, options: [{ ar: 'أ) تحسين صورة الإدارة أمام المجتمع', en: 'A' }, { ar: 'ب) دعم العملية التعليمية وتحقيق مصلحة الطلاب', en: 'B' }, { ar: 'ج) تخفيف العبء عن المدير', en: 'C' }], correctAnswer: '1' },
    { id: 'q28', type: 'multiple-choice', questionText: { ar: 'من وسائل تعزيز الأخلاق في الإدارة:', en: 'Boosting admin ethics:' }, options: [{ ar: 'أ) تجاهل السلوكيات السلبية', en: 'A' }, { ar: 'ب) وضع مواثيق سلوك واضحة', en: 'B' }, { ar: 'ج) تقليل الاجتماعات', en: 'C' }], correctAnswer: '1' },
    { id: 'q29', type: 'multiple-choice', questionText: { ar: 'من التحديات التي تواجه الإدارة الأخلاقية:', en: 'Admin ethics challenges:' }, options: [{ ar: 'أ) الفساد الإداري والمحاباة', en: 'A' }, { ar: 'ب) زيادة الوعي المهني', en: 'B' }, { ar: 'ج) وجود تدريب مهني فعال', en: 'C' }], correctAnswer: '0' },
    { id: 'q30', type: 'multiple-choice', questionText: { ar: 'من الأخلاقيات التي يجب على المعلم الالتزام بها مع الإدارة:', en: 'Teacher-Admin ethics:' }, options: [{ ar: 'أ) تجاهل اللوائح والقوانين', en: 'A' }, { ar: 'ب) الالتزام باللوائح والتعليمات الرسمية', en: 'B' }, { ar: 'ج) الاعتماد على الزملاء', en: 'C' }], correctAnswer: '1' },
    { id: 'q31', type: 'multiple-choice', questionText: { ar: 'من الاعتقادات الخاطئة حول أخلاقيات المهنة:', en: 'Misconceptions:' }, options: [{ ar: 'أ) مسألة دينية فقط تخص علاقة العبد بربة', en: 'A' }, { ar: 'ب) أنها قضية إدارية بحته', en: 'B' }, { ar: 'ج) أنها نظام أخلاقي عام', en: 'C' }], correctAnswer: '0' },
    { id: 'q32', type: 'multiple-choice', questionText: { ar: 'أخلاقيات المهنة ترتبط أساساً:', en: 'Ethics link to:' }, options: [{ ar: 'أ) حقوق الآخرين', en: 'A' }, { ar: 'ب) التزامات المعلم', en: 'B' }, { ar: 'ج) العادات الاجتماعية', en: 'C' }], correctAnswer: '1' },
    { id: 'q33', type: 'multiple-choice', questionText: { ar: 'دور المعلم في وضع أخلاقيات العمل:', en: 'Teacher role in setting ethics:' }, options: [{ ar: 'أ) المعلم شريك في وضعها وتطبيقها', en: 'A' }, { ar: 'ب) المدير هو صاحب القرار الوحيد', en: 'B' }, { ar: 'ج) لا علاقة للمعلم بها', en: 'C' }], correctAnswer: '0' },
    { id: 'q34', type: 'multiple-choice', questionText: { ar: 'القوانين واللوائح لا تكفي وحدها لأنها:', en: 'Laws insufficiency:' }, options: [{ ar: 'أ) لا تطبق دائماً', en: 'A' }, { ar: 'ب) عامة ولا تعالج التفاصيل الأخلاقية', en: 'B' }, { ar: 'ج) تتغير باستمرار', en: 'C' }], correctAnswer: '1' },
    { id: 'q35', type: 'multiple-choice', questionText: { ar: 'من القيم التي كان يعتز بها العرب قبل الإسلام:', en: 'Pre-Islamic Arabic values:' }, options: [{ ar: 'أ) الصبر والزهد', en: 'A' }, { ar: 'ب) الكرم والشجاعة والوفاء', en: 'B' }, { ar: 'ج) العمل الجماعي', en: 'C' }], correctAnswer: '1' },
    { id: 'q36', type: 'multiple-choice', questionText: { ar: 'السلوك المهني الجيد يظهر في:', en: 'Good prof behavior:' }, options: [{ ar: 'أ) احترام الأنظمة والتعليمات', en: 'A' }, { ar: 'ب) تجاهل القوانين', en: 'B' }, { ar: 'ج) التهاون في الوقت', en: 'C' }], correctAnswer: '0' },

    // --- (2) 35 True/False Questions ---
    { id: 'q37', type: 'true-false', questionText: { ar: 'الأخلاقيات المهنية جزء منفصل تمامًا عن الأخلاق العامة.', en: 'Statement 1' }, options: [{ ar: 'صح', en: 'True' }, { ar: 'خطأ', en: 'False' }], correctAnswer: '1' },
    { id: 'q38', type: 'true-false', questionText: { ar: 'النظرية الاكتسابية ترى أن الأخلاق قابلة للتغيير من خلال التربية والتعليم.', en: 'Statement 2' }, options: [{ ar: 'صح', en: 'True' }, { ar: 'خطأ', en: 'False' }], correctAnswer: '0' },
    { id: 'q39', type: 'true-false', questionText: { ar: 'الفعل الخلقي يصح اعتباره أخلاقيًا حتى لو صدر بالإكراه أو التهديد.', en: 'Statement 3' }, options: [{ ar: 'صح', en: 'True' }, { ar: 'خطأ', en: 'False' }], correctAnswer: '1' },
    { id: 'q40', type: 'true-false', questionText: { ar: 'وسائل الإعلام قد تكون مصدرًا للقيم الأخلاقية.', en: 'Statement 4' }, options: [{ ar: 'صح', en: 'True' }, { ar: 'خطأ', en: 'False' }], correctAnswer: '0' },
    { id: 'q41', type: 'true-false', questionText: { ar: 'النظرية الفطرية تعتبر أن الأخلاق قابلة للتغيير باستمرار.', en: 'Statement 5' }, options: [{ ar: 'صح', en: 'True' }, { ar: 'خطأ', en: 'False' }], correctAnswer: '1' },
    { id: 'q42', type: 'true-false', questionText: { ar: 'الوظيفة لا تتطلب أي معرفة أو تعليم متخصص.', en: 'Statement 6' }, options: [{ ar: 'صح', en: 'True' }, { ar: 'خطأ', en: 'False' }], correctAnswer: '0' },
    { id: 'q43', type: 'true-false', questionText: { ar: 'ليس من الضروري المحافظة على وقت العمل.', en: 'Statement 7' }, options: [{ ar: 'صح', en: 'True' }, { ar: 'خطأ', en: 'False' }], correctAnswer: '1' },
    { id: 'q44', type: 'true-false', questionText: { ar: 'الهدف من أخلاقيات المهنة فهم السلوك الوظيفي.', en: 'Statement 8' }, options: [{ ar: 'صح', en: 'True' }, { ar: 'خطأ', en: 'False' }], correctAnswer: '0' },
    { id: 'q45', type: 'true-false', questionText: { ar: 'الاخلاص والأمانة والتواضع هي سلوكيات غير مطلوبة في العمل المهني.', en: 'Statement 9' }, options: [{ ar: 'صح', en: 'True' }, { ar: 'خطأ', en: 'False' }], correctAnswer: '1' },
    { id: 'q46', type: 'true-false', questionText: { ar: 'المصدر الإداري التنظيمي من مصادر أخلاقيات المهنة.', en: 'Statement 10' }, options: [{ ar: 'صح', en: 'True' }, { ar: 'خطأ', en: 'False' }], correctAnswer: '0' },
    { id: 'q47', type: 'true-false', questionText: { ar: 'من المرتكزات الاساسية لأخلاقيات المهنة الامتناع التام عن المساعدة في أعمال السوء أو التحريض عليها أو المشاركة فيها.', en: 'Statement 11' }, options: [{ ar: 'صح', en: 'True' }, { ar: 'خطأ', en: 'False' }], correctAnswer: '0' },
    { id: 'q48', type: 'true-false', questionText: { ar: 'يعد عدم إدلاء العاملين ببيانات او مطالبات مضللة ومزيفة بخصوص مؤهلاتهم المهنية او خبراتهم من أحدي الالتزامات تجاه المهنة.', en: 'Statement 12' }, options: [{ ar: 'صح', en: 'True' }, { ar: 'خطأ', en: 'False' }], correctAnswer: '0' },
    { id: 'q49', type: 'true-false', questionText: { ar: 'تكمن أهمية أخلاقيات المهنة في المستوي الفرد فقط.', en: 'Statement 13' }, options: [{ ar: 'صح', en: 'True' }, { ar: 'خطأ', en: 'False' }], correctAnswer: '1' },
    { id: 'q50', type: 'true-false', questionText: { ar: 'من إحدى وسائل ترسيخ أخلاقيات المهنة تنمية الرقابة الذاتية والقدوة الحسنة.', en: 'Statement 14' }, options: [{ ar: 'صح', en: 'True' }, { ar: 'خطأ', en: 'False' }], correctAnswer: '0' },
    { id: 'q51', type: 'true-false', questionText: { ar: 'تتمثل تحديات أخلاقيات المهنة في التحديات الخارجية فقط.', en: 'Statement 15' }, options: [{ ar: 'صح', en: 'True' }, { ar: 'خطأ', en: 'False' }], correctAnswer: '1' },
    { id: 'q52', type: 'true-false', questionText: { ar: 'أخلاقيات مهنة التعليم تقتصر على العلاقة بين المعلم والطلاب فقط.', en: 'Statement 16' }, options: [{ ar: 'صح', en: 'True' }, { ar: 'خطأ', en: 'False' }], correctAnswer: '1' },
    { id: 'q53', type: 'true-false', questionText: { ar: 'يجب على المعلم احترام جميع الطلاب بغض النظر عن خلفياتهم.', en: 'Statement 17' }, options: [{ ar: 'صح', en: 'True' }, { ar: 'خطأ', en: 'False' }], correctAnswer: '0' },
    { id: 'q54', type: 'true-false', questionText: { ar: 'من حق المعلم استخدام العقاب البدني مع الطلاب.', en: 'Statement 18' }, options: [{ ar: 'صح', en: 'True' }, { ar: 'خطأ', en: 'False' }], correctAnswer: '1' },
    { id: 'q55', type: 'true-false', questionText: { ar: 'الصدق والأمانة من أساسيات مهنة التعليم.', en: 'Statement 19' }, options: [{ ar: 'صح', en: 'True' }, { ar: 'خطأ', en: 'False' }], correctAnswer: '0' },
    { id: 'q56', type: 'true-false', questionText: { ar: 'لا يشترط في المعلم أن يكون قدوة للطلاب.', en: 'Statement 20' }, options: [{ ar: 'صح', en: 'True' }, { ar: 'خطأ', en: 'False' }], correctAnswer: '1' },
    { id: 'q57', type: 'true-false', questionText: { ar: 'العدالة من أهم المبادئ الأخلاقية في مهنة التعليم.', en: 'Statement 21' }, options: [{ ar: 'صح', en: 'True' }, { ar: 'خطأ', en: 'False' }], correctAnswer: '0' },
    { id: 'q58', type: 'true-false', questionText: { ar: 'التمييز بين الطلاب يعزز الثقة بينهم.', en: 'Statement 22' }, options: [{ ar: 'صح', en: 'True' }, { ar: 'خطأ', en: 'False' }], correctAnswer: '1' },
    { id: 'q59', type: 'true-false', questionText: { ar: 'على المعلم أن يتعلم باستمرار ويطور نفسه مهنيًا.', en: 'Statement 23' }, options: [{ ar: 'صح', en: 'True' }, { ar: 'خطأ', en: 'False' }], correctAnswer: '0' },
    { id: 'q60', type: 'true-false', questionText: { ar: 'المعلم القدوة يؤثر في سلوك طلابه بالإيجاب.', en: 'Statement 24' }, options: [{ ar: 'صح', en: 'True' }, { ar: 'خطأ', en: 'False' }], correctAnswer: '0' },
    { id: 'q61', type: 'true-false', questionText: { ar: 'يمكن للمعلم أن يتجاهل القواعد الأخلاقية في حالات الطوارئ.', en: 'Statement 25' }, options: [{ ar: 'صح', en: 'True' }, { ar: 'خطأ', en: 'False' }], correctAnswer: '1' },
    { id: 'q62', type: 'true-false', questionText: { ar: 'وجود ميثاق أخلاقي واضح في المدرسة يعزز الالتزام والانضباط.', en: 'Statement 26' }, options: [{ ar: 'صح', en: 'True' }, { ar: 'خطأ', en: 'False' }], correctAnswer: '0' },
    { id: 'q63', type: 'true-false', questionText: { ar: 'ضعف الرقابة الذاتية من التحديات التي تواجه الإدارة الأخلاقية.', en: 'Statement 27' }, options: [{ ar: 'صح', en: 'True' }, { ar: 'خطأ', en: 'False' }], correctAnswer: '0' },
    { id: 'q64', type: 'true-false', questionText: { ar: 'احترام الطلاب جزء من أخلاقيات المعلم المهنية.', en: 'Statement 28' }, options: [{ ar: 'صح', en: 'True' }, { ar: 'خطأ', en: 'False' }], correctAnswer: '0' },
    { id: 'q65', type: 'true-false', questionText: { ar: 'المعلم القدوة هو الذي يجسد القيم في أفعاله لا في أقواله فقط.', en: 'Statement 29' }, options: [{ ar: 'صح', en: 'True' }, { ar: 'خطأ', en: 'False' }], correctAnswer: '0' },
    { id: 'q66', type: 'true-false', questionText: { ar: 'القدوة الحسنة في الإدارة تُؤثر إيجابًا على سلوك العاملين.', en: 'Statement 30' }, options: [{ ar: 'صح', en: 'True' }, { ar: 'خطأ', en: 'False' }], correctAnswer: '0' },
    { id: 'q67', type: 'true-false', questionText: { ar: 'أخلاقيات المهنة قضية دينية فقط لا علاقة لها بالإدارة.', en: 'Statement 31' }, options: [{ ar: 'صح', en: 'True' }, { ar: 'خطأ', en: 'False' }], correctAnswer: '1' },
    { id: 'q68', type: 'true-false', questionText: { ar: 'المعلم مسؤول عن تطبيق القواعد الأخلاقية ومشارك في وضعها.', en: 'Statement 32' }, options: [{ ar: 'صح', en: 'True' }, { ar: 'خطأ', en: 'False' }], correctAnswer: '0' },
    { id: 'q69', type: 'true-false', questionText: { ar: 'القوانيين وحدها كافية لضبط السلوك المهني.', en: 'Statement 33' }, options: [{ ar: 'صح', en: 'True' }, { ar: 'خطأ', en: 'False' }], correctAnswer: '1' },
    { id: 'q70', type: 'true-false', questionText: { ar: 'يمكن اكتساب الأخلاق المهنية بالتدريب والممارسة.', en: 'Statement 34' }, options: [{ ar: 'صح', en: 'True' }, { ar: 'خطأ', en: 'False' }], correctAnswer: '0' },
    { id: 'q71', type: 'true-false', questionText: { ar: 'الاعتداء اللفظي على الطلاب مخالفة أخلاقية وجنائية.', en: 'Statement 35' }, options: [{ ar: 'صح', en: 'True' }, { ar: 'خطأ', en: 'False' }], correctAnswer: '0' },

    // --- (3) 21 Fill-in-the-Blank Questions ---
    { id: 'q72', type: 'fill-in-the-blank', questionText: { ar: '........ هي مجموعة من القواعد والأصول المتعارف عليها بين أصحاب المهنة.', en: 'F-1' }, correctAnswer: 'أخلاقيات المهنة' },
    { id: 'q73', type: 'fill-in-the-blank', questionText: { ar: 'النظرية الفطرية ترى أن الأخلاق ........ وثابتة، بينما النظرية الاكتسابية ترى أنها ........ من خلال التربية والتعليم والتجارب.', en: 'F-2' }, correctAnswer: 'فطرية، مكتسبة' },
    { id: 'q74', type: 'fill-in-the-blank', questionText: { ar: 'الشروط اللازمة في الفعل الخلقي أن يصدر ........ وبإرادة ........ حرة.', en: 'F-3' }, correctAnswer: 'بتكرار، إرادة' },
    { id: 'q75', type: 'fill-in-the-blank', questionText: { ar: 'المهنة تتمتع بوضع ........ و ........ أعلى من الوظيفة.', en: 'F-4' }, correctAnswer: 'اجتماعي، اقتصادي' },
    { id: 'q76', type: 'fill-in-the-blank', questionText: { ar: 'من مبادئ أخلاقيات المهنة ........ و ........', en: 'F-5' }, correctAnswer: 'المعاملة الحسنة، الاستقامة' },
    { id: 'q77', type: 'fill-in-the-blank', questionText: { ar: 'من مصادر أخلاقيات المهنة المصدر ........ و ........ و ........', en: 'F-6' }, correctAnswer: 'الديني، الاجتماعي، السياسي' },
    { id: 'q78', type: 'fill-in-the-blank', questionText: { ar: 'تستند أخلاقيات المهنة علي جملة من ........ و ........ الأساسية.', en: 'F-7' }, correctAnswer: 'المبادئ، المرتكزات' },
    { id: 'q79', type: 'fill-in-the-blank', questionText: { ar: 'من وسائل ترسيخ أخلاقيات المهنة ........ و ........', en: 'F-8' }, correctAnswer: 'القدوة الحسنة، تنمية الرقابة الذاتية' },
    { id: 'q80', type: 'fill-in-the-blank', questionText: { ar: 'تشمل تحديات أخلاقيات المهنة تحديات ........ و ........', en: 'F-9' }, correctAnswer: 'داخلية، خارجية' },
    { id: 'q81', type: 'fill-in-the-blank', questionText: { ar: 'تعد مهنة التعليم من أسمى المهن لأنها ........', en: 'F-10' }, correctAnswer: 'تغرس القيم الأخلاقية' },
    { id: 'q82', type: 'fill-in-the-blank', questionText: { ar: 'من القيم الأخلاقية التي يجب أن يتحلى بها المعلم ........', en: 'F-11' }, correctAnswer: 'الصدق والأمانة' },
    { id: 'q83', type: 'fill-in-the-blank', questionText: { ar: 'دور المعلم في الصف لا يقتصر على التعليم بل يشمل ........', en: 'F-12' }, correctAnswer: 'التربية وغرس القيم' },
    { id: 'q84', type: 'fill-in-the-blank', questionText: { ar: 'احترام خصوصية الطالب من مظاهر ........', en: 'F-13' }, correctAnswer: 'الأمانة المهنية' },
    { id: 'q85', type: 'fill-in-the-blank', questionText: { ar: 'يجب أن يكون المعلم ........ في أدائه وسلوكه.', en: 'F-14' }, correctAnswer: 'قدوة' },
    { id: 'q86', type: 'fill-in-the-blank', questionText: { ar: 'النزاهة في التعليم تعني أداء العمل بصدق ........', en: 'F-15' }, correctAnswer: 'دون تحيز أو غش' },
    { id: 'q87', type: 'fill-in-the-blank', questionText: { ar: 'البيئة الصفية الأخلاقية تقوم على ........ و ........', en: 'F-16' }, correctAnswer: 'الاحترام - الثقة المتبادلة' },
    { id: 'q88', type: 'fill-in-the-blank', questionText: { ar: '........ هي مجموعة القيم والمبادئ التي توجه سلوك المديرين والعاملين في المؤسسات التعليمية، وتضمن أداء المهام بروح العدالة والنزاهة والمسؤولية.', en: 'F-17' }, correctAnswer: 'أخلاقيات الإدارة التعليمية' },
    { id: 'q89', type: 'fill-in-the-blank', questionText: { ar: '........ هي أن يكون المدير والمعلم نموذجا يحتذى به في السلوك، والالتزام والاحترام والانضباط المهني داخل المدرسة.', en: 'F-18' }, correctAnswer: 'القدوة الحسنة' },
    { id: 'q90', type: 'fill-in-the-blank', questionText: { ar: '........ هي معاملة الطلاب أو الزملاء بطريقة غير عادلة على أساس الجنس أو الدين أو الأصل أو الحالة الاجتماعية.', en: 'F-19' }, correctAnswer: 'التمييز والتحيز' },
    { id: 'q91', type: 'fill-in-the-blank', questionText: { ar: '........ سلوك غير لائق كالتدخين أو التمييز ضد الطلاب.', en: 'F-20' }, correctAnswer: 'المخالفة الأخلاقية' },
    { id: 'q92', type: 'fill-in-the-blank', questionText: { ar: 'تصرفات المعلم التي تعكس التزامه بالقيم المهنية ........', en: 'F-21' }, correctAnswer: 'السلوك المهني' }
  ]
};

export const TRANSLATIONS = {
  ar: {
    dashboard: 'الرئيسية',
    startExam: 'ابدأ الامتحان الشامل',
    totalExams: 'إجمالي الاختبارات',
    accuracy: 'معدل الدقة',
    progress: 'نسبة التقدم',
    lastScore: 'آخر درجة',
    noExams: 'لا توجد اختبارات متاحة',
    next: 'السؤال التالي',
    previous: 'السؤال السابق',
    submit: 'إنهاء الاختبار',
    backToHome: 'العودة للرئيسية',
    score: 'درجتك النهائية',
    timeSpent: 'الوقت',
    correctAnswers: 'إجابات صحيحة',
    wrongAnswers: 'إجابات خاطئة',
    review: 'مراجعة الأسئلة',
    checking: 'يتم التصحيح بالذكاء الاصطناعي...',
    check: 'تحقق من صحة الإجابة',
    yourAnswer: 'إجابتك',
    correctAnswer: 'الإجابة الصحيحة',
    langToggle: 'English',
    admin_login: 'دخول المسؤول',
    username: 'اسم المستخدم',
    password: 'كلمة السر',
    login_btn: 'دخول',
    cancel: 'إلغاء',
    invalid_creds: 'بيانات خاطئة',
    admin_control: 'لوحة التحكم للمسؤول',
    exit_admin: 'خروج من الإدارة',
    upload_success: 'تم الحفظ بنجاح',
    preparing: 'جاري التحضير...',
    admin_badge: 'إدارة',
    exam_builder: 'بناء اختبار جديد',
    exam_info: 'بيانات الاختبار',
    exam_title: 'عنوان الاختبار',
    select_subject: 'اختر المادة',
    add_question: 'إضافة سؤال',
    question_text: 'نص السؤال',
    question_type: 'نوع السؤال',
    options_label: 'خيارات الإجابة',
    add_option: 'إضافة خيار',
    save_exam: 'حفظ الاختبار ونشره',
    mcq: 'اختياري',
    tf: 'صح/خطأ',
    fill: 'مقالي/أكمل',
    import_file: 'استيراد من ملف',
    no_questions: 'لا توجد أسئلة',
    active_exams: 'الاختبارات النشطة',
    hidden_exams: 'المخفية',
    upload_image: 'صورة مصغرة',
    saved_questions: 'المواد والملفات',
    folders: 'موادي التعليمية',
    create_folder: 'إنشاء مادة جديدة',
    folder_name: 'اسم المادة (مثلاً: ريادة أعمال)',
    save_folder: 'حفظ المادة',
    practice_folder: 'بدء تدريب شامل',
    download_pdf: 'تحميل كـ PDF',
    save_to_folder: 'حفظ في ملف',
    bulk_save_wrong: 'حفظ الأخطاء لمراجعتها',
    review_folder: 'مراجعة الأخطاء',
    no_folders: 'لا توجد مواد مضافة بعد',
    delete_folder: 'حذف المجلد',
    edit_folder: 'تعديل',
    fav_questions: 'سؤال محفوظ'
  },
  en: {
    dashboard: 'Dashboard',
    startExam: 'Start Final Exam',
    totalExams: 'Total Exams',
    accuracy: 'Accuracy',
    progress: 'Progress',
    lastScore: 'Last Score',
    noExams: 'No exams available',
    next: 'Next Question',
    previous: 'Previous',
    submit: 'Finish',
    backToHome: 'Back Home',
    score: 'Final Score',
    timeSpent: 'Time',
    correctAnswers: 'Correct',
    wrongAnswers: 'Wrong',
    review: 'Review',
    checking: 'Correcting by AI...',
    check: 'Check Answer',
    yourAnswer: 'Your Answer',
    correctAnswer: 'Correct Answer',
    langToggle: 'العربية',
    admin_login: 'Admin Login',
    username: 'Username',
    password: 'Password',
    login_btn: 'Login',
    cancel: 'Cancel',
    invalid_creds: 'Invalid',
    admin_control: 'Admin Control',
    exit_admin: 'Exit Admin',
    upload_success: 'Saved successfully',
    preparing: 'Preparing...',
    admin_badge: 'ADMIN',
    exam_builder: 'New Exam Builder',
    exam_info: 'Exam Info',
    exam_title: 'Exam Title',
    select_subject: 'Select Subject',
    add_question: 'Add Question',
    question_text: 'Question Text',
    question_type: 'Type',
    options_label: 'Options',
    add_option: 'Add Option',
    save_exam: 'Save & Publish',
    mcq: 'MCQ',
    tf: 'T/F',
    fill: 'Fill in Blank',
    import_file: 'Import',
    no_questions: 'No questions',
    active_exams: 'Active',
    hidden_exams: 'Hidden',
    upload_image: 'Thumbnail',
    saved_questions: 'My Files',
    folders: 'Folders',
    create_folder: 'Create New Subject',
    folder_name: 'Subject Name',
    save_folder: 'Save Folder',
    practice_folder: 'Start Practice',
    download_pdf: 'Download PDF',
    save_to_folder: 'Save to File',
    bulk_save_wrong: 'Save Mistakes',
    review_folder: 'Review Mistakes',
    no_folders: 'No folders added',
    delete_folder: 'Delete',
    edit_folder: 'Edit',
    fav_questions: 'Saved Questions'
  }
};
