import { Subject, Exam } from './types';

export const SUBJECTS: Subject[] = [];

export const ETHICS_EXAM: Exam = {
  id: 'ethics_101',
  subjectId: 'ethics',
  title: { ar: 'امتحان أخلاقيات المهنة الشامل', en: 'Professional Ethics Exam' },
  active: true,
  thumbnail: '⚖️',
  questions: [
    // --- (1) 35 Multiple Choice Questions ---
    { id: 'q1', type: 'multiple-choice', questionText: { ar: '1- مفهوم الأخلاق هو:', en: 'The concept of ethics is:' }, options: [{ ar: 'أ) مجموعة من القيم والمبادئ التي تحدد سلوك الفرد وتوجهه', en: 'A) Set of values and principles' }, { ar: 'ب) قواعد سياسية لضبط سلوك الدولة', en: 'B) Only government laws' }, { ar: 'ج) قوانين مهنية تنظم العلاقة بين أصحاب المهن', en: 'C) Old traditions' }], correctAnswer: '0' },
    { id: 'q2', type: 'multiple-choice', questionText: { ar: '2- النظرية الفطرية الطبيعية ترى أن:', en: 'Innate theory sees that:' }, options: [{ ar: 'أ) الأخلاق مكتسبة بالتجربة', en: 'A) Ethics change by society' }, { ar: 'ب) الأخلاق ثابتة نابعة من ذات الإنسان وفطرته', en: 'B) Ethics are innate and fixed' }, { ar: 'ج) الأخلاق لا علاقة لها بالتربية', en: 'C) Ethics are fully acquired' }], correctAnswer: '1' },
    { id: 'q3', type: 'multiple-choice', questionText: { ar: '3- يشترط بالفعل الخلقي حتى يكون دليلاً على الأخلاق أن:', en: 'Requirement for a moral act:' }, options: [{ ar: 'أ) يصدر بتكرار وبإرادة حرة', en: 'A) Repetitive and free will' }, { ar: 'ب) يكون مرة واحدة فقط', en: 'B) Occurs only once' }, { ar: 'ج) يصدر بالإكراه', en: 'C) Occurs under coercion' }], correctAnswer: '0' },
    { id: 'q4', type: 'multiple-choice', questionText: { ar: '4- من وسائل اكتساب الأخلاق:', en: 'Means of acquiring ethics:' }, options: [{ ar: 'أ) التعليم والخبرة الشخصية', en: 'A) Education and experience' }, { ar: 'ب) الاستسلام للوراثة فقط', en: 'B) Only biological inheritance' }, { ar: 'ج) تجاهل القيم المجتمعية', en: 'C) Strict laws' }], correctAnswer: '0' },
    { id: 'q5', type: 'multiple-choice', questionText: { ar: '5- العلاقة بين الأخلاق العامة وأخلاقيات المهنة هي:', en: 'Relation between general and prof ethics:' }, options: [{ ar: 'أ) الأخلاق العامة جزء من أخلاقيات المهنة', en: 'A) No relation' }, { ar: 'ب) أخلاقيات المهنة جزء من الأخلاق العامة', en: 'B) Prof ethics is part of general ethics' }, { ar: 'ج) لا توجد علاقة بينهما', en: 'C) General is part of prof' }], correctAnswer: '1' },
    { id: 'q6', type: 'multiple-choice', questionText: { ar: '6- النظرية الاكتسابية تعتبر أن الإنسان يولد:', en: 'Acquisition theory: Man is born:' }, options: [{ ar: 'أ) ممتلئا بالأخلاق الفاضلة', en: 'A) With all ethics' }, { ar: 'ب) ممتلئا بالأخلاق السيئة', en: 'B) Evil by nature' }, { ar: 'ج) صفحة بيضاء يكتسب منها الأخلاق بالتربية والتجارب', en: 'C) Blank slate' }], correctAnswer: '2' },
    { id: 'q7', type: 'multiple-choice', questionText: { ar: '7- مجموعة من السمات الأساسية التي تتطلب مهارة عالية ومعرفة متخصصة:', en: 'Traits requiring high skill and knowledge:' }, options: [{ ar: 'أ) المهنة', en: 'A) Profession' }, { ar: 'ب) الوظيفة', en: 'B) Hobby' }, { ar: 'ج) العمل', en: 'C) Simple job' }], correctAnswer: '0' },
    { id: 'q8', type: 'multiple-choice', questionText: { ar: '8- أن يستحضر الشخص النية الصالحة في العمل:', en: 'Having good intentions at work:' }, options: [{ ar: 'أ) التواضع', en: 'A) Flattery' }, { ar: 'ب) الصدق', en: 'B) Speed' }, { ar: 'ج) الإخلاص', en: 'C) Sincerity' }], correctAnswer: '2' },
    { id: 'q9', type: 'multiple-choice', questionText: { ar: '9- خلق يعف الإنسان عما ليس له به حق:', en: 'Refraining from what is not yours:' }, options: [{ ar: 'أ) الصدق', en: 'A) Courage' }, { ar: 'ب) الأمانة', en: 'B) Integrity/Honesty' }, { ar: 'ج) الاخلاص', en: 'C) Generosity' }], correctAnswer: '1' },
    { id: 'q10', type: 'multiple-choice', questionText: { ar: '10- من مصادر أخلاقيات المهنة:', en: 'Sources of prof ethics:' }, options: [{ ar: 'أ) المصدر الاقتصادي', en: 'A) Economic source' }, { ar: 'ب) المصدر الديني', en: 'B) Religious source' }, { ar: 'ج) جميع ما سبق', en: 'C) All of the above' }], correctAnswer: '1' },
    { id: 'q11', type: 'multiple-choice', questionText: { ar: '11- تعمل على وقاية الفرد من الإنحراف وتدعم الثقة في النفس وثقته بالمنظمة والمجتمع:', en: 'Prevents deviation and supports self-confidence:' }, options: [{ ar: 'أ) أهمية أخلاقيات المهنة على مستوى الفرد', en: 'A) Importance at individual level' }, { ar: 'ب) أهمية أخلاقيات المهنة على مستوي المجتمع', en: 'B) Criminal laws' }, { ar: 'ج) أهمية أخلاقيات المهنة على مستوي العمل', en: 'C) High salary' }], correctAnswer: '0' },
    { id: 'q12', type: 'multiple-choice', questionText: { ar: '12- يدعم الرضا والاستقرار الاجتماعي بين غالبية الناس حيث يحصل كل ذي حق علي حقة ويسود العدل:', en: 'Supports social stability and justice:' }, options: [{ ar: 'أ) أهمية أخلاقيات المهنة علي مستوي الفرد', en: 'A) Fierce competition' }, { ar: 'ب) أهمية أخلاقيات المهنة على مستوى المجتمع', en: 'B) Importance at social level' }, { ar: 'ج) أهمية أخلاقيات المهنة على مستوي العمل', en: 'C) Increased taxes' }], correctAnswer: '1' },
    { id: 'q13', type: 'multiple-choice', questionText: { ar: '13- تساعد في فهم الواجبات المهنية والتذكير بنظام الثواب والعقاب كإحدي الوسائل الناجحة:', en: 'Helps understand duties and rewards system:' }, options: [{ ar: 'أ) أهمية أخلاقيات المهنة علي مستوي الفرد', en: 'A) Leisure activities' }, { ar: 'ب) أهمية أخلاقيات المهنة علي مستوي المجتمع', en: 'B) Advertisements' }, { ar: 'ج) أهمية أخلاقيات المهنة على مستوى العمل', en: 'C) Importance at work level' }], correctAnswer: '2' },
    { id: 'q14', type: 'multiple-choice', questionText: { ar: '14- من وسائل ترسيخ أخلاقيات المهنة:', en: 'Means of consolidating prof ethics:' }, options: [{ ar: 'أ) القدوة الحسنة', en: 'A) Good role model' }, { ar: 'ب) استغلال المنصب', en: 'B) Only financial fines' }, { ar: 'ج) الهدايا والضيافة', en: 'C) Ignoring mistakes' }], correctAnswer: '0' },
    { id: 'q15', type: 'multiple-choice', questionText: { ar: '15- الانفراد بالرأي أو التسلط من تحديات أخلاقيات المهنة:', en: 'Tyranny and isolation of opinion:' }, options: [{ ar: 'أ) التحديات الداخلية', en: 'A) Internal challenges' }, { ar: 'ب) التحديات الخارجية', en: 'B) External challenges' }, { ar: 'ج) التحديات العامة', en: 'C) Economic challenges' }], correctAnswer: '0' },
    { id: 'q16', type: 'multiple-choice', questionText: { ar: '16- تعد مهنة التعليم مهنة سامية لأنها تقوم على:', en: 'Teaching is noble because it builds:' }, options: [{ ar: 'أ) نقل المعلومات فقط', en: 'A) Fast profit' }, { ar: 'ب) تحقيق الأرباح', en: 'B) Fame' }, { ar: 'ج) بناء الإنسان وتنمية القيم', en: 'C) Building humans and values' }], correctAnswer: '2' },
    { id: 'q17', type: 'multiple-choice', questionText: { ar: '17- من أهم أخلاقيات مهنة التعليم:', en: 'Core teaching ethics:' }, options: [{ ar: 'أ) التحيز لبعض الطلاب', en: 'A) Secret grades' }, { ar: 'ب) العدالة والإنصاف', en: 'B) Justice and fairness' }, { ar: 'ج) الغش', en: 'C) Discriminating' }], correctAnswer: '1' },
    { id: 'q18', type: 'multiple-choice', questionText: { ar: '18- احترام التنوع بين الطلاب يعني أن المعلم:', en: 'Respecting student diversity means:' }, options: [{ ar: 'أ) يفرق في المعاملة', en: 'A) Ignoring weak students' }, { ar: 'ب) يتجاهل الفروق الفردية', en: 'B) Favoring locals' }, { ar: 'ج) يعامل الطلاب بعدالة واحترام', en: 'C) Treats all with respect' }], correctAnswer: '2' },
    { id: 'q19', type: 'multiple-choice', questionText: { ar: '19- من صفات المعلم القدوة الأخلاقية:', en: 'Role model teacher traits:' }, options: [{ ar: 'أ) العصبية الدائمة', en: 'A) Constant anger' }, { ar: 'ب) الصبر والعدل', en: 'B) Patience and justice' }, { ar: 'ج) التهاون', en: 'C) Neglecting appearance' }], correctAnswer: '1' },
    { id: 'q20', type: 'multiple-choice', questionText: { ar: '20- من واجبات المعلم تجاه طلابه:', en: 'Teacher duties towards students:' }, options: [{ ar: 'أ) كشف أسرارهم', en: 'A) Revealing secrets' }, { ar: 'ب) الاستهزاء بهم', en: 'B) Ignoring problems' }, { ar: 'ج) احترام خصوصيتهم', en: 'C) Respecting privacy' }], correctAnswer: '2' },
    { id: 'q21', type: 'multiple-choice', questionText: { ar: '21- الصدق في تقييم الطلاب يعني أن المعلم:', en: 'Honesty in evaluation means:' }, options: [{ ar: 'أ) يجامل الطلاب', en: 'A) Giving free high grades' }, { ar: 'ب) يقيمهم وفق معايير عادلة', en: 'B) Evaluating by fair standards' }, { ar: 'ج) يعتمد على الحظ', en: 'C) Favoring relatives' }], correctAnswer: '1' },
    { id: 'q22', type: 'multiple-choice', questionText: { ar: '22- العدالة في التعليم تظهر عندما:', en: 'Justice in education appears when:' }, options: [{ ar: 'أ) يفضل المعلم المتفوقين فقط', en: 'A) Focusing only on smart ones' }, { ar: 'ب) يساوي بين جميع الطلاب', en: 'B) Equality between all' }, { ar: 'ج) يتعامل بحدة مع الجميع', en: 'C) Giving private lessons' }], correctAnswer: '1' },
    { id: 'q23', type: 'multiple-choice', questionText: { ar: '23- من الأخلاقيات الواجب تجنبها في مهنة التعليم:', en: 'Ethics to avoid in teaching:' }, options: [{ ar: 'أ) الأمانة', en: 'A) Humility' }, { ar: 'ب) التحيز', en: 'B) Bias/Partiality' }, { ar: 'ج) الصبر', en: 'C) Cooperation' }], correctAnswer: '1' },
    { id: 'q24', type: 'multiple-choice', questionText: { ar: '24- يجب على المعلم أن يكون نموذجا:', en: 'Teacher must be a model in:' }, options: [{ ar: 'أ) في السلوك المهني والأخلاقي', en: 'A) Prof and moral behavior' }, { ar: 'ب) في التفوق الدراسي فقط', en: 'B) Wealth' }, { ar: 'ج) في الحزم الشديد فقط', en: 'C) Sports only' }], correctAnswer: '0' },
    { id: 'q25', type: 'multiple-choice', questionText: { ar: '25- من مهام المعلم الأخلاقية داخل الصف:', en: 'Moral tasks in class:' }, options: [{ ar: 'أ) فرض رأيه فقط', en: 'A) Forcing silence' }, { ar: 'ب) تشجيع الحوار والنقاش', en: 'B) Encouraging dialogue' }, { ar: 'ج) تجاهل آراء الطلاب', en: 'C) Just reading books' }], correctAnswer: '1' },
    { id: 'q26', type: 'multiple-choice', questionText: { ar: '26- ما المقصود بأخلاقيات الإدارة التعليمية:', en: 'Educational admin ethics means:' }, options: [{ ar: 'أ) القوانين المنظمة للعمل فقط', en: 'A) School profit' }, { ar: 'ب) القيم والمبادئ التي تحكم السلوك الإداري', en: 'B) Admin behavior principles' }, { ar: 'ج) التعليمات الوزارية', en: 'C) New buildings' }], correctAnswer: '1' },
    { id: 'q27', type: 'multiple-choice', questionText: { ar: '27- التعاون مع أولياء الأمور والمجتمع المحلي يهدف إلى:', en: 'Cooperation with parents aims to:' }, options: [{ ar: 'أ) تحسين صورة الإدارة أمام المجتمع', en: 'A) Fees increase' }, { ar: 'ب) دعم العملية التعليمية وتحقيق مصلحة الطلاب', en: 'B) Support education/students' }, { ar: 'ج) تخفيف العبء عن المدير', en: 'C) Trips only' }], correctAnswer: '1' },
    { id: 'q28', type: 'multiple-choice', questionText: { ar: '28- من وسائل تعزيز الأخلاق في الإدارة:', en: 'Promoting admin ethics via:' }, options: [{ ar: 'أ) تجاهل السلوكيات السلبية', en: 'A) More hours' }, { ar: 'ب) وضع مواثيق سلوك واضحة', en: 'B) Clear conduct codes' }, { ar: 'ج) تقليل الاجتماعات', en: 'C) Lower salaries' }], correctAnswer: '1' },
    { id: 'q29', type: 'multiple-choice', questionText: { ar: '29- من التحديات التي تواجه الإدارة الأخلاقية:', en: 'Moral admin challenges:' }, options: [{ ar: 'أ) الفساد الإداري والمحاباة', en: 'A) Corruption and favoritism' }, { ar: 'ب) زيادة الوعي المهني', en: 'B) Tech progress' }, { ar: 'ج) وجود تدريب مهني فعال', en: 'C) More students' }], correctAnswer: '0' },
    { id: 'q30', type: 'multiple-choice', questionText: { ar: '30- من الأخلاقيات التي يجب على المعلم الالتزام بها مع الإدارة:', en: 'Teacher ethics with admin:' }, options: [{ ar: 'أ) تجاهل اللوائح والقوانين', en: 'A) Being late' }, { ar: 'ب) الالتزام باللوائح والتعليمات الرسمية', en: 'B) Following official rules' }, { ar: 'ج) الاعتماد على الزملاء', en: 'C) Ignoring decisions' }], correctAnswer: '1' },
    { id: 'q31', type: 'multiple-choice', questionText: { ar: '31- من الاعتقادات الخاطئة حول أخلاقيات المهنة:', en: 'Misconceptions about prof ethics:' }, options: [{ ar: 'أ) مسألة دينية فقط تخص علاقة العبد بربة', en: 'A) Only religious issue' }, { ar: 'ب) أنها قضية إدارية بحته', en: 'B) Improves productivity' }, { ar: 'ج) أنها نظام أخلاقي عام', en: 'C) Necessary for society' }], correctAnswer: '0' },
    { id: 'q32', type: 'multiple-choice', questionText: { ar: '32- أخلاقيات المهنة ترتبط أساساً بـ:', en: 'Prof ethics related to:' }, options: [{ ar: 'أ) حقوق الآخرين', en: 'A) Rights of others' }, { ar: 'ب) التزامات المعلم', en: 'B) Self interest' }, { ar: 'ج) العادات الاجتماعية', en: 'C) Time wasting' }], correctAnswer: '1' },
    { id: 'q33', type: 'multiple-choice', questionText: { ar: '33- دور المعلم في وضع أخلاقيات العمل:', en: 'Teacher role in work ethics:' }, options: [{ ar: 'أ) المعلم شريك في وضعها وتطبيقها', en: 'A) Partner in setup/app' }, { ar: 'ب) المدير هو صاحب القرار الوحيد', en: 'B) Just executor' }, { ar: 'ج) لا علاقة للمعلم بها', en: 'C) No role' }], correctAnswer: '0' },
    { id: 'q34', type: 'multiple-choice', questionText: { ar: '34- القوانين واللوائح لا تكفي وحدها لأنها:', en: 'Laws are not enough because:' }, options: [{ ar: 'أ) لا تطبق دائماً', en: 'A) Hard to understand' }, { ar: 'ب) عامة ولا تعالج التفاصيل الأخلاقية', en: 'B) General, lacks details' }, { ar: 'ج) تتغير باستمرار', en: 'C) Changes daily' }], correctAnswer: '1' },
    { id: 'q35', type: 'multiple-choice', questionText: { ar: '35- من القيم التي كان يعتز بها العرب قبل الإسلام:', en: 'Pre-Islamic Arabic values:' }, options: [{ ar: 'أ) الصبر والزهد', en: 'A) Laziness' }, { ar: 'ب) الكرم والشجاعة والوفاء', en: 'B) Generosity, courage, loyalty' }, { ar: 'ج) العمل الجماعي', en: 'C) Dependency' }], correctAnswer: '1' },

    // --- (2) 35 True/False Questions ---
    { id: 'q37', type: 'true-false', questionText: { ar: 'أخلاقيات المهنة جزء منفصل تمامًا عن الأخلاق العامة.', en: 'Prof ethics is totally separate from general ethics.' }, options: [{ ar: 'صح', en: 'True' }, { ar: 'خطأ', en: 'False' }], correctAnswer: '1' },
    { id: 'q38', type: 'true-false', questionText: { ar: 'النظرية الاكتسابية ترى أن الأخلاق قابلة للتغيير من خلال التربية والتعليم.', en: 'Acquisition theory: Ethics can change via education.' }, options: [{ ar: 'صح', en: 'True' }, { ar: 'خطأ', en: 'False' }], correctAnswer: '0' },
    { id: 'q39', type: 'true-false', questionText: { ar: 'الفعل الخلقي يصح اعتباره أخلاقيًا حتى لو صدر بالإكراه أو التهديد.', en: 'Moral act counts even if forced.' }, options: [{ ar: 'صح', en: 'True' }, { ar: 'خطأ', en: 'False' }], correctAnswer: '1' },
    { id: 'q40', type: 'true-false', questionText: { ar: 'وسائل الإعلام قد تكون مصدرًا للقيم الأخلاقية.', en: 'Media can be a source of ethics.' }, options: [{ ar: 'صح', en: 'True' }, { ar: 'خطأ', en: 'False' }], correctAnswer: '0' },
    { id: 'q41', type: 'true-false', questionText: { ar: 'النظرية الفطرية تعتبر أن الأخلاق قابلة للتغيير باستمرار.', en: 'Innate theory: Ethics change constantly.' }, options: [{ ar: 'صح', en: 'True' }, { ar: 'خطأ', en: 'False' }], correctAnswer: '1' },
    { id: 'q42', type: 'true-false', questionText: { ar: 'الوظيفة لا تتطلب أي معرفة أو تعليم متخصص.', en: 'Job requires no specialized knowledge.' }, options: [{ ar: 'صح', en: 'True' }, { ar: 'خطأ', en: 'False' }], correctAnswer: '0' },
    { id: 'q43', type: 'true-false', questionText: { ar: 'ليس من الضروري المحافظة على وقت العمل.', en: 'Keeping work time is unnecessary.' }, options: [{ ar: 'صح', en: 'True' }, { ar: 'خطأ', en: 'False' }], correctAnswer: '1' },
    { id: 'q44', type: 'true-false', questionText: { ar: 'الهدف من أخلاقيات المهنة فهم السلوك الوظيفي.', en: 'Goal of prof ethics: understand behavior.' }, options: [{ ar: 'صح', en: 'True' }, { ar: 'خطأ', en: 'False' }], correctAnswer: '0' },
    { id: 'q45', type: 'true-false', questionText: { ar: 'الاخلاص والأمانة والتواضع هي سلوكيات غير مطلوبة في العمل المهني.', en: 'Sincerity and honesty are not required at work.' }, options: [{ ar: 'صح', en: 'True' }, { ar: 'خطأ', en: 'False' }], correctAnswer: '1' },
    { id: 'q46', type: 'true-false', questionText: { ar: 'المصدر الإداري التنظيمي من مصادر أخلاقيات المهنة.', en: 'Org admin is a source of prof ethics.' }, options: [{ ar: 'صح', en: 'True' }, { ar: 'خطأ', en: 'False' }], correctAnswer: '0' },
    { id: 'q47', type: 'true-false', questionText: { ar: 'من المرتكزات الأساسية لأخلاقيات المهنة الامتناع التام عن المساعدة في أعمال السوء أو التحريض عليها أو المشاركة فيها.', en: 'Abstaining from helping in bad acts is a pillar.' }, options: [{ ar: 'صح', en: 'True' }, { ar: 'خطأ', en: 'False' }], correctAnswer: '0' },
    { id: 'q48', type: 'true-false', questionText: { ar: 'عدم إدلاء العاملين ببيانات مضللة بخصوص مؤهلاتهم التزام مهني.', en: 'Not giving misleading data is a prof commitment.' }, options: [{ ar: 'صح', en: 'True' }, { ar: 'خطأ', en: 'False' }], correctAnswer: '0' },
    { id: 'q49', type: 'true-false', questionText: { ar: 'تكمن أهمية أخلاقيات المهنة في المستوى الفردي فقط.', en: 'Prof ethics importance is only individual.' }, options: [{ ar: 'صح', en: 'True' }, { ar: 'خطأ', en: 'False' }], correctAnswer: '1' },
    { id: 'q50', type: 'true-false', questionText: { ar: 'من إحدى وسائل ترسيخ أخلاقيات المهنة تنمية الرقابة الذاتية والقدوة الحسنة.', en: 'Self-monitoring and models consolidate ethics.' }, options: [{ ar: 'صح', en: 'True' }, { ar: 'خطأ', en: 'False' }], correctAnswer: '0' },
    { id: 'q51', type: 'true-false', questionText: { ar: 'تتمثل تحديات أخلاقيات المهنة في التحديات الخارجية فقط.', en: 'Prof ethics challenges are only external.' }, options: [{ ar: 'صح', en: 'True' }, { ar: 'خطأ', en: 'False' }], correctAnswer: '1' },
    { id: 'q52', type: 'true-false', questionText: { ar: 'أخلاقيات مهنة التعليم تقتصر على العلاقة بين المعلم والطلاب فقط.', en: 'Teaching ethics are only teacher-student.' }, options: [{ ar: 'صح', en: 'True' }, { ar: 'خطأ', en: 'False' }], correctAnswer: '1' },
    { id: 'q53', type: 'true-false', questionText: { ar: 'يجب على المعلم احترام جميع الطلاب بغض النظر عن خلفياتهم.', en: 'Teacher must respect all students.' }, options: [{ ar: 'صح', en: 'True' }, { ar: 'خطأ', en: 'False' }], correctAnswer: '0' },
    { id: 'q54', type: 'true-false', questionText: { ar: 'من حق المعلم استخدام العقاب البدني مع الطلاب.', en: 'Teacher has right to use corporal punishment.' }, options: [{ ar: 'صح', en: 'True' }, { ar: 'خطأ', en: 'False' }], correctAnswer: '1' },
    { id: 'q55', type: 'true-false', questionText: { ar: 'الصدق والأمانة من أساسيات مهنة التعليم.', en: 'Honesty and integrity are basics.' }, options: [{ ar: 'صح', en: 'True' }, { ar: 'خطأ', en: 'False' }], correctAnswer: '0' },
    { id: 'q56', type: 'true-false', questionText: { ar: 'لا يشترط في المعلم أن يكون قدوة للطلاب.', en: 'Teacher doesn\'t need to be a role model.' }, options: [{ ar: 'صح', en: 'True' }, { ar: 'خطأ', en: 'False' }], correctAnswer: '1' },
    { id: 'q57', type: 'true-false', questionText: { ar: 'العدالة من أهم المبادئ الأخلاقية في مهنة التعليم.', en: 'Justice is a main principle in teaching.' }, options: [{ ar: 'صح', en: 'True' }, { ar: 'خطأ', en: 'False' }], correctAnswer: '0' },
    { id: 'q58', type: 'true-false', questionText: { ar: 'التمييز بين الطلاب يعزز الثقة بينهم.', en: 'Discrimination builds trust.' }, options: [{ ar: 'صح', en: 'True' }, { ar: 'خطأ', en: 'False' }], correctAnswer: '1' },
    { id: 'q59', type: 'true-false', questionText: { ar: 'على المعلم أن يتعلم باستمرار ويطور نفسه مهنيًا.', en: 'Teacher must constantly learn and develop.' }, options: [{ ar: 'صح', en: 'True' }, { ar: 'خطأ', en: 'False' }], correctAnswer: '0' },
    { id: 'q60', type: 'true-false', questionText: { ar: 'المعلم القدوة يؤثر في سلوك طلابه بالإيجاب.', en: 'Role model teacher affects behavior positively.' }, options: [{ ar: 'صح', en: 'True' }, { ar: 'خطأ', en: 'False' }], correctAnswer: '0' },
    { id: 'q61', type: 'true-false', questionText: { ar: 'يمكن للمعلم أن يتجاهل القواعد الأخلاقية في حالات الطوارئ.', en: 'Teacher can ignore ethics in emergencies.' }, options: [{ ar: 'صح', en: 'True' }, { ar: 'خطأ', en: 'False' }], correctAnswer: '1' },
    { id: 'q62', type: 'true-false', questionText: { ar: 'وجود ميثاق أخلاقي واضح في المدرسة يعزز الالتزام والانضباط.', en: 'Clear code of ethics boosts discipline.' }, options: [{ ar: 'صح', en: 'True' }, { ar: 'خطأ', en: 'False' }], correctAnswer: '0' },
    { id: 'q63', type: 'true-false', questionText: { ar: 'ضعف الرقابة الذاتية من التحديات التي تواجه الإدارة الأخلاقية.', en: 'Weak self-monitoring is a challenge.' }, options: [{ ar: 'صح', en: 'True' }, { ar: 'خطأ', en: 'False' }], correctAnswer: '0' },
    { id: 'q64', type: 'true-false', questionText: { ar: 'احترام الطلاب جزء من أخلاقيات المعلم المهنية.', en: 'Student respect is part of teacher ethics.' }, options: [{ ar: 'صح', en: 'True' }, { ar: 'خطأ', en: 'False' }], correctAnswer: '0' },
    { id: 'q65', type: 'true-false', questionText: { ar: 'المعلم القدوة هو الذي يجسد القيم في أفعاله لا في أقواله فقط.', en: 'Teacher model embodies values in acts.' }, options: [{ ar: 'صح', en: 'True' }, { ar: 'خطأ', en: 'False' }], correctAnswer: '0' },
    { id: 'q66', type: 'true-false', questionText: { ar: 'القدوة الحسنة في الإدارة تُؤثر إيجابًا على سلوك العاملين.', en: 'Good admin model affects staff behavior.' }, options: [{ ar: 'صح', en: 'True' }, { ar: 'خطأ', en: 'False' }], correctAnswer: '0' },
    { id: 'q67', type: 'true-false', questionText: { ar: 'أخلاقيات المهنة قضية دينية فقط لا علاقة لها بالإدارة.', en: 'Prof ethics is religious only.' }, options: [{ ar: 'صح', en: 'True' }, { ar: 'خطأ', en: 'False' }], correctAnswer: '1' },
    { id: 'q68', type: 'true-false', questionText: { ar: 'المعلم مسؤول عن تطبيق القواعد الأخلاقية ومشارك في وضعها.', en: 'Teacher is responsible for applying ethics.' }, options: [{ ar: 'صح', en: 'True' }, { ar: 'خطأ', en: 'False' }], correctAnswer: '0' },
    { id: 'q69', type: 'true-false', questionText: { ar: 'القوانيين وحدها كافية لضبط السلوك المهني.', en: 'Laws alone are enough for behavior.' }, options: [{ ar: 'صح', en: 'True' }, { ar: 'خطأ', en: 'False' }], correctAnswer: '1' },
    { id: 'q70', type: 'true-false', questionText: { ar: 'يمكن اكتساب الأخلاق المهنية بالتدريب والممارسة.', en: 'Prof ethics can be acquired by training.' }, options: [{ ar: 'صح', en: 'True' }, { ar: 'خطأ', en: 'False' }], correctAnswer: '0' },
    { id: 'q71', type: 'true-false', questionText: { ar: 'الاعتداء اللفظي على الطلاب مخالفة أخلاقية وجنائية.', en: 'Verbal abuse is a violation.' }, options: [{ ar: 'صح', en: 'True' }, { ar: 'خطأ', en: 'False' }], correctAnswer: '0' },

    // --- (3) 21 Fill-in-the-Blank Questions ---
    { id: 'q72', type: 'fill-in-the-blank', questionText: { ar: '1- ........ هي مجموعة من القواعد والأصول المتعارف عليها بين أصحاب المهنة.', en: 'Set of rules known between professionals.' }, correctAnswer: 'أخلاقيات المهنة' },
    { id: 'q73', type: 'fill-in-the-blank', questionText: { ar: '2- النظرية الفطرية ترى أن الأخلاق ........ وثابتة، بينما النظرية الاكتسابية ترى أنها ........ من خلال التربية والتعليم والتجارب.', en: 'Innate theory: Fixed, Acquisition: Acquired.' }, correctAnswer: 'فطرية، مكتسبة' },
    { id: 'q74', type: 'fill-in-the-blank', questionText: { ar: '3- الشروط اللازمة في الفعل الخلقي أن يصدر ........ وبإرادة ........ حرة.', en: 'Moral act must be repetitive and free will.' }, correctAnswer: 'بتكرار، إرادة' },
    { id: 'q75', type: 'fill-in-the-blank', questionText: { ar: '4- المهنة تتمتع بوضع ........ و ........ أعلى من الوظيفة.', en: 'Profession has higher social and economic status.' }, correctAnswer: 'اجتماعي، اقتصادي' },
    { id: 'q76', type: 'fill-in-the-blank', questionText: { ar: '5- من مبادئ أخلاقيات المهنة ........ و ........', en: 'Principles: Good treatment and integrity.' }, correctAnswer: 'المعاملة الحسنة، الاستقامة' },
    { id: 'q77', type: 'fill-in-the-blank', questionText: { ar: '6- من مصادر أخلاقيات المهنة المصدر ........ و ........ و ........', en: 'Sources: Religious, Social, Political.' }, correctAnswer: 'الديني، الاجتماعي، السياسي' },
    { id: 'q78', type: 'fill-in-the-blank', questionText: { ar: '7- تستند أخلاقيات المهنة علي جملة من ........ و ........ الأساسية.', en: 'Based on principles and pillars.' }, correctAnswer: 'المبادئ، المرتكزات' },
    { id: 'q79', type: 'fill-in-the-blank', questionText: { ar: '8- من وسائل ترسيخ أخلاقيات المهنة ........ و ........', en: 'Means: Good model and self-monitoring.' }, correctAnswer: 'القدوة الحسنة، تنمية الرقابة الذاتية' },
    { id: 'q80', type: 'fill-in-the-blank', questionText: { ar: '9- تشمل تحديات أخلاقيات المهنة تحديات ........ و ........', en: 'Challenges: Internal and External.' }, correctAnswer: 'داخلية، خارجية' },
    { id: 'q81', type: 'fill-in-the-blank', questionText: { ar: '10- تعد مهنة التعليم من أسمى المهن لأنها ........', en: 'Teaching noble because it plants ethics.' }, correctAnswer: 'تغرس القيم الأخلاقية' },
    { id: 'q82', type: 'fill-in-the-blank', questionText: { ar: '11- من القيم الأخلاقية التي يجب أن يتحلى بها المعلم ........', en: 'Teacher values: Honesty and integrity.' }, correctAnswer: 'الصدق والأمانة' },
    { id: 'q83', type: 'fill-in-the-blank', questionText: { ar: '12- دور المعلم في الصف لا يقتصر على التعليم بل يشمل ........', en: 'Teacher role: Education and values.' }, correctAnswer: 'التربية وغرس القيم' },
    { id: 'q84', type: 'fill-in-the-blank', questionText: { ar: '13- احترام خصوصية الطالب من مظاهر ........', en: 'Respecting student privacy: prof integrity.' }, correctAnswer: 'الأمانة المهنية' },
    { id: 'q85', type: 'fill-in-the-blank', questionText: { ar: '14- يجب أن يكون المعلم ........ في أدائه وسلوكه.', en: 'Teacher must be a model in behavior.' }, correctAnswer: 'قدوة' },
    { id: 'q86', type: 'fill-in-the-blank', questionText: { ar: '15- النزاهة في التعليم تعني أداء العمل بصدق ........', en: 'Integrity means honest work without bias.' }, correctAnswer: 'دون تحيز أو غش' },
    { id: 'q87', type: 'fill-in-the-blank', questionText: { ar: '16- البيئة الصفية الأخلاقية تقوم على ........ و ........', en: 'Classroom environment based on respect and trust.' }, correctAnswer: 'الاحترام - الثقة المتبادلة' },
    { id: 'q88', type: 'fill-in-the-blank', questionText: { ar: '17- ........ هي مجموعة القيم والمبادئ التي توجه سلوك المديرين والعاملين في المؤسسات التعليمية، وتضمن أداء المهام بروح العدالة والنزاهة والمسؤولية.', en: 'Educational admin ethics.' }, correctAnswer: 'أخلاقيات الإدارة التعليمية' },
    { id: 'q89', type: 'fill-in-the-blank', questionText: { ar: '18- ........ هي أن يكون المدير والمعلم نموذجا يحتذى به في السلوك، والالتزام والاحترام والانضباط المهني داخل المدرسة.', en: 'Good role model.' }, correctAnswer: 'القدوة الحسنة' },
    { id: 'q90', type: 'fill-in-the-blank', questionText: { ar: '19- ........ هي معاملة الطلاب أو الزملاء بطريقة غير عادلة على أساس الجنس أو الدين أو الأصل أو الحالة الاجتماعية.', en: 'Discrimination and bias.' }, correctAnswer: 'التمييز والتحيز' },
    { id: 'q91', type: 'fill-in-the-blank', questionText: { ar: '20- ........ سلوك غير لائق كالتدخين أو التمييز ضد الطلاب.', en: 'Moral violation.' }, correctAnswer: 'المخالفة الأخلاقية' },
    { id: 'q92', type: 'fill-in-the-blank', questionText: { ar: '21- تصرفات المعلم التي تعكس التزامه بالقيم المهنية ........', en: 'Teacher prof behavior.' }, correctAnswer: 'السلوك المهني' }
  ]
};

export const TRANSLATIONS = {
  ar: {
    dashboard: 'الرئيسية',
    startExam: 'ابدأ الامتحان الشامل',
    // ... rest of translations remain same
    totalExams: 'إجمالي الاختبارات',
    accuracy: 'معدل الدقة',
    progress: 'نسبة التقدم',
    lastScore: 'آخر درجة',
    noExams: 'لا توجد اختبارات متاحة',
    next: 'السؤال التالي',
    previous: 'السؤال السابق',
    submit: 'إنهاء الاختبار',
    backToHome: 'العودة للرئيسية',
    score: 'درجتك النهائية',
    timeSpent: 'الوقت',
    correctAnswers: 'إجابات صحيحة',
    wrongAnswers: 'إجابات خاطئة',
    review: 'مراجعة الأسئلة',
    checking: 'يتم التصحيح بالذكاء الاصطناعي...',
    check: 'تحقق من صحة الإجابة',
    yourAnswer: 'إجابتك',
    correctAnswer: 'الإجابة الصحيحة',
    langToggle: 'English',
    admin_login: 'دخول المسؤول',
    username: 'اسم المستخدم',
    password: 'كلمة السر',
    login_btn: 'دخول',
    cancel: 'إلغاء',
    invalid_creds: 'بيانات خاطئة',
    admin_control: 'لوحة التحكم للمسؤول',
    exit_admin: 'خروج من الإدارة',
    upload_success: 'تم الحفظ بنجاح',
    preparing: 'جاري التحضير...',
    admin_badge: 'إدارة',
    exam_builder: 'بناء اختبار جديد',
    exam_info: 'بيانات الاختبار',
    exam_title: 'عنوان الاختبار',
    select_subject: 'اختر المادة',
    add_question: 'إضافة سؤال',
    question_text: 'نص السؤال',
    question_type: 'نوع السؤال',
    options_label: 'خيارات الإجابة',
    add_option: 'إضافة خيار',
    save_exam: 'حفظ الاختبار ونشره',
    mcq: 'اختياري',
    tf: 'صح/خطأ',
    fill: 'مقالي/أكمل',
    import_file: 'استيراد من ملف',
    no_questions: 'لا توجد أسئلة',
    active_exams: 'الاختبارات النشطة',
    hidden_exams: 'المخفية',
    upload_image: 'صورة مصغرة',
    saved_questions: 'المواد والملفات',
    folders: 'موادي التعليمية',
    create_folder: 'إنشاء مادة جديدة',
    folder_name: 'اسم المادة (مثلاً: ريادة أعمال)',
    save_folder: 'حفظ المادة',
    practice_folder: 'بدء تدريب شامل',
    download_pdf: 'تحميل كـ PDF',
    save_to_folder: 'حفظ في ملف',
    bulk_save_wrong: 'حفظ الأخطاء لمراجعتها',
    review_folder: 'مراجعة الأخطاء',
    no_folders: 'لا توجد مواد مضافة بعد',
    delete_folder: 'حذف المجلد',
    edit_folder: 'تعديل',
    fav_questions: 'سؤال محفوظ'
  },
  en: {
    dashboard: 'Dashboard',
    startExam: 'Start Final Exam',
    totalExams: 'Total Exams',
    accuracy: 'Accuracy',
    progress: 'Progress',
    lastScore: 'Last Score',
    noExams: 'No exams available',
    next: 'Next Question',
    previous: 'Previous',
    submit: 'Finish',
    backToHome: 'Back Home',
    score: 'Final Score',
    timeSpent: 'Time',
    correctAnswers: 'Correct',
    wrongAnswers: 'Wrong',
    review: 'Review',
    checking: 'Correcting by AI...',
    check: 'Check Answer',
    yourAnswer: 'Your Answer',
    correctAnswer: 'Correct Answer',
    langToggle: 'العربية',
    admin_login: 'Admin Login',
    username: 'Username',
    password: 'Password',
    login_btn: 'Login',
    cancel: 'Cancel',
    invalid_creds: 'Invalid',
    admin_control: 'Admin Control',
    exit_admin: 'Exit Admin',
    upload_success: 'Saved successfully',
    preparing: 'Preparing...',
    admin_badge: 'ADMIN',
    exam_builder: 'New Exam Builder',
    exam_info: 'Exam Info',
    exam_title: 'Exam Title',
    select_subject: 'Select Subject',
    add_question: 'Add Question',
    question_text: 'Question Text',
    question_type: 'Type',
    options_label: 'Options',
    add_option: 'Add Option',
    save_exam: 'Save & Publish',
    mcq: 'MCQ',
    tf: 'T/F',
    fill: 'Fill in Blank',
    import_file: 'Import',
    no_questions: 'No questions',
    active_exams: 'Active',
    hidden_exams: 'Hidden',
    upload_image: 'Thumbnail',
    saved_questions: 'My Files',
    folders: 'Folders',
    create_folder: 'Create New Subject',
    folder_name: 'Subject Name',
    save_folder: 'Save Folder',
    practice_folder: 'Start Practice',
    download_pdf: 'Download PDF',
    save_to_folder: 'Save to File',
    bulk_save_wrong: 'Save Mistakes',
    review_folder: 'Review Mistakes',
    no_folders: 'No folders added',
    delete_folder: 'Delete',
    edit_folder: 'Edit',
    fav_questions: 'Saved Questions'
  }
};